export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS"
export const PRODUCT_QUANTITY = "PRODUCT_QUANTITY"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";